INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (1,'137-34','non','curae',05,'Jaskolski and Sons');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (2,'976-60','viverra','erat',02,'Rath-Collier');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (3,'790-08','ut','ut',31,'Walsh-Lockman');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (4,'320-18','metus','mattis',37,'Stark-Bayer');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (5,'598-87','posuere','ullamcorper',84,'Labadie-Swift');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (6,'432-83','sociis','massa',25,'McGlynn-Willms');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (7,'822-46','pede','ut',67,'Zieme, Kirlin and Gibson');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (8,'686-69','consequat','massa',52,'Donnelly and Sons');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (9,'060-55','iaculis','sem',73,'Abernathy Inc');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (10,'332-38','maecenas','aliquet',25,'Kohler Inc');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (11,'151-82','condimentum','velit',37,'Ondricka-Kuvalis');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (12,'182-65','morbi','orci',74,'Willms, Bahringer and Beier');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (13,'164-72','curabitur','quisque',38,'Herzog LLC');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (14,'512-09','rutrum','id',52,'Mertz-Erdman');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (15,'690-08','in','at',73,'Cremin-Raynor');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (16,'842-56','cras','pretium',32,'Dickens-Gutmann');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (17,'011-10','aliquet','luctus',28,'Ruecker, Reichert and Lubowitz');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (18,'892-64','ac','nam',96,'Heathcote-O''Keefe');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (19,'338-88','venenatis','elit',08,'Leuschke, Simonis and Bode');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (20,'835-75','tristique','ultrices',24,'Stanton-O''Conner');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (21,'944-73','erat','dui',68,'Hudson-Von');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (22,'599-01','primis','rhoncus',74,'Kuhn, Schoen and Jast');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (23,'890-50','condimentum','in',39,'Lang Inc');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (24,'074-51','aenean','vestibulum',86,'Borer Group');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (25,'367-64','nunc','lacus',12,'Champlin and Sons');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (26,'402-73','integer','erat',35,'Krajcik, Mertz and Kunze');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (27,'375-41','diam','ultrices',18,'Walsh Group');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (28,'627-08','ultrices','volutpat',85,'Macejkovic-Corwin');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (29,'240-77','proin','sed',52,'Moen-Murphy');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (30,'977-97','consequat','aliquet',22,'Windler, Greenholt and Bins');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (31,'353-67','volutpat','non',01,'Nikolaus-Littel');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (32,'059-50','nisl','non',51,'Hettinger, Harvey and Hackett');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (33,'352-50','praesent','libero',22,'DuBuque Group');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (34,'238-74','ut','justo',34,'Howe-Skiles');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (35,'134-88','mi','est',05,'Corkery-Stanton');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (36,'661-25','ipsum','lorem',52,'Schulist, Kunze and Bosco');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (37,'728-89','lacinia','purus',16,'Hettinger, Feeney and Maggio');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (38,'142-76','odio','quis',50,'Schmidt, Bernhard and Cremin');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (39,'516-63','integer','luctus',29,'Kemmer-O''Reilly');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (40,'231-90','consequat','cras',26,'Balistreri Group');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (41,'726-80','mattis','id',91,'Block and Sons');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (42,'340-64','in','cursus',63,'Prosacco-Gerlach');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (43,'859-89','quisque','in',91,'Leannon-Haag');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (44,'327-85','ante','suspendisse',31,'Rath and Sons');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (45,'890-51','proin','odio',30,'Dickinson, Yundt and Rath');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (46,'163-07','nec','augue',91,'Ferry, Heathcote and Mante');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (47,'415-17','semper','ornare',79,'Kuhn-Kshlerin');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (48,'981-43','turpis','odio',79,'Frami-Franecki');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (49,'968-21','maecenas','pellentesque',85,'Leffler Group');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (50,'017-80','in','habitasse',06,'Kovacek, Bashirian and Schiller');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (51,'480-11','felis','pulvinar',45,'O''Hara, Walker and Kautzer');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (52,'683-07','natoque','nulla',56,'Goyette and Sons');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (53,'153-43','ac','morbi',39,'Torp and Sons');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (54,'136-68','lacinia','lorem',13,'Bode Inc');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (55,'961-60','quis','dui',51,'Huels Inc');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (56,'309-72','duis','massa',57,'Beer and Sons');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (57,'966-98','fusce','pede',63,'Weimann LLC');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (58,'482-07','enim','venenatis',73,'Gislason LLC');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (59,'275-53','pede','cras',12,'Hermiston-Casper');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (60,'397-12','praesent','ridiculus',26,'Halvorson-Goodwin');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (61,'235-93','donec','pulvinar',18,'Schroeder Group');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (62,'314-24','mauris','morbi',20,'Keeling, Hyatt and Purdy');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (63,'541-23','orci','interdum',31,'Wuckert, Bogan and Fadel');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (64,'314-15','vitae','vestibulum',60,'Hoeger, Bednar and Jacobs');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (65,'199-58','porttitor','primis',09,'Haley-Quitzon');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (66,'084-87','nulla','diam',26,'Strosin and Sons');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (67,'028-60','venenatis','cursus',27,'Fay, Wolf and Gutkowski');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (68,'233-23','eget','purus',04,'Runolfsdottir-Smith');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (69,'566-07','luctus','elementum',61,'Stiedemann, Schulist and Wilderman');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (70,'595-39','ac','justo',70,'Stamm Group');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (71,'384-22','nascetur','diam',94,'Wilderman, Gutkowski and Gislason');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (72,'155-29','donec','tempus',80,'Mosciski Inc');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (73,'509-75','eget','massa',76,'Bins-Nicolas');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (74,'641-08','nulla','neque',14,'Fisher, Wiegand and Gerhold');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (75,'972-98','ipsum','diam',93,'Hartmann-Raynor');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (76,'189-46','dapibus','adipiscing',78,'Barrows-Stamm');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (77,'696-03','penatibus','vulputate',61,'Larkin Inc');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (78,'711-67','rhoncus','ipsum',84,'Morar-Batz');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (79,'023-23','pede','blandit',73,'Quigley, Franecki and Hilpert');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (80,'172-74','sit','nullam',62,'Nicolas, Jenkins and Rolfson');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (81,'366-76','magna','arcu',83,'Deckow, Grimes and Hane');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (82,'092-15','praesent','mauris',41,'King-Lakin');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (83,'479-66','erat','justo',80,'Bernhard Group');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (84,'944-06','posuere','convallis',85,'Bechtelar, Boehm and Cummerata');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (85,'435-22','posuere','magna',22,'Stehr-Schowalter');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (86,'368-38','a','mi',07,'Schaefer, Beer and Kuhic');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (87,'481-57','aliquam','in',61,'Walker LLC');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (88,'123-09','justo','nisi',76,'Cassin Group');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (89,'958-02','nisi','faucibus',89,'Douglas, Konopelski and Stoltenberg');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (90,'482-01','interdum','ipsum',26,'Greenfelder, Cartwright and Grady');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (91,'788-56','gravida','eu',54,'Torp Inc');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (92,'398-67','mauris','sollicitudin',94,'Orn, Labadie and Goldner');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (93,'956-32','maecenas','suspendisse',15,'Turner, Klocko and Stamm');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (94,'745-36','ac','ultrices',67,'Legros Group');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (95,'568-59','interdum','interdum',53,'Pagac-Murphy');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (96,'697-28','lacus','in',17,'Walsh Group');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (97,'296-67','nec','praesent',13,'Wilderman-Howell');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (98,'495-27','orci','augue',32,'Smith LLC');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (99,'269-13','massa','blandit',39,'Lynch, Rowe and VonRueden');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (100,'234-25','nulla','interdum',75,'Wiegand and Sons');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (101,'935-88','orci','at',37,'Kohler-Steuber');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (102,'645-95','purus','curae',08,'Huels-Stehr');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (103,'043-76','luctus','neque',60,'Brown-Maggio');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (104,'825-21','sit','metus',73,'Torp-Gulgowski');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (105,'590-61','vestibulum','sed',62,'Senger Group');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (106,'418-20','ipsum','commodo',77,'Lesch and Sons');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (107,'365-46','donec','aliquam',45,'Padberg-Daugherty');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (108,'423-48','et','volutpat',51,'Fritsch-Rosenbaum');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (109,'011-36','consectetuer','mauris',51,'Shanahan, Orn and Lueilwitz');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (110,'339-11','etiam','proin',54,'Pollich, Koelpin and Cassin');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (111,'062-24','ac','fermentum',01,'Dickens, Lind and Emard');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (112,'663-16','sociis','donec',76,'Torp, Rice and Ankunding');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (113,'521-19','id','augue',98,'Howell Group');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (114,'037-59','tortor','in',81,'Cronin Inc');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (115,'620-85','rutrum','ipsum',31,'Green, Medhurst and Daugherty');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (116,'133-32','placerat','amet',66,'Legros, Kilback and Jacobson');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (117,'307-67','ut','ante',20,'Mertz, Senger and Wiegand');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (118,'675-05','morbi','natoque',35,'Rogahn, Torphy and Metz');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (119,'990-23','gravida','morbi',14,'Nader LLC');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (120,'341-68','aliquam','consequat',54,'Hills and Sons');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (121,'117-78','libero','tempor',98,'Flatley and Sons');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (122,'194-82','eu','nullam',30,'Bartell Group');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (123,'997-82','a','mus',59,'Braun, Schneider and Mosciski');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (124,'218-87','tellus','vestibulum',57,'Hansen Inc');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (125,'168-19','odio','sed',32,'Mante LLC');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (126,'083-93','consequat','turpis',23,'Witting, Oberbrunner and Hamill');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (127,'359-37','nulla','luctus',22,'Osinski-Doyle');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (128,'522-29','mauris','sit',05,'Schulist-Gulgowski');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (129,'657-74','nunc','morbi',99,'Kessler Inc');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (130,'937-89','penatibus','velit',85,'Daugherty-Schimmel');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (131,'509-89','at','donec',64,'Corkery-Torphy');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (132,'899-92','sed','sapien',04,'Cronin-Senger');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (133,'274-55','semper','ante',38,'Gibson Group');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (134,'285-49','sit','lorem',30,'Bechtelar-Pacocha');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (135,'831-33','nulla','diam',78,'Tromp-Nitzsche');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (136,'791-78','erat','amet',70,'Turner-Blick');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (137,'023-03','ut','imperdiet',04,'Moore, Von and Kuhlman');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (138,'203-01','suscipit','in',71,'Stamm, Block and Schroeder');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (139,'091-54','interdum','nulla',81,'Buckridge LLC');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (140,'719-48','sed','quam',13,'Stanton, O''Hara and VonRueden');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (141,'914-52','in','nullam',15,'Kilback, Bailey and Pouros');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (142,'833-07','quam','habitasse',01,'Mann-Lesch');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (143,'701-88','natoque','sollicitudin',39,'Dooley-Davis');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (144,'965-73','vel','molestie',27,'White, Buckridge and Gutmann');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (145,'560-38','neque','vel',51,'Douglas-Herman');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (146,'511-03','vestibulum','nunc',22,'McCullough, Wehner and Harris');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (147,'991-22','justo','in',57,'Homenick, Fahey and Wolf');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (148,'773-34','mauris','integer',62,'Collins LLC');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (149,'278-34','felis','vitae',57,'Harber, Oberbrunner and Reichert');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (150,'157-90','sit','porttitor',84,'Hartmann-Lehner');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (151,'005-94','habitasse','aliquam',33,'Schimmel, Torphy and O''Hara');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (152,'000-18','enim','blandit',63,'Dare and Sons');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (153,'265-97','est','convallis',29,'Herman and Sons');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (154,'180-95','augue','consectetuer',61,'Ziemann-Wuckert');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (155,'258-33','consequat','in',69,'Predovic, Huels and Kulas');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (156,'804-31','felis','ac',97,'Quitzon Inc');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (157,'549-96','enim','ut',01,'Volkman, Jacobs and Koelpin');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (158,'991-44','placerat','sed',64,'Kessler, Frami and Wisoky');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (159,'966-08','aenean','nulla',14,'Kuhn LLC');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (160,'445-88','non','justo',22,'Pollich-Labadie');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (161,'572-73','nulla','duis',79,'Reilly-Blanda');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (162,'672-16','vulputate','vel',82,'Lang and Sons');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (163,'061-70','eu','at',40,'Reichel-Balistreri');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (164,'235-65','non','mi',56,'Stokes, Mayert and Jerde');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (165,'881-56','lobortis','ut',96,'Crooks-Keeling');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (166,'217-10','amet','convallis',69,'Langworth-Robel');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (167,'394-24','ut','molestie',62,'Rodriguez, Thiel and Shields');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (168,'682-14','mus','vulputate',92,'Schulist-Prohaska');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (169,'438-90','tellus','arcu',24,'Von-Grady');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (170,'161-49','nibh','scelerisque',00,'Zemlak Group');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (171,'937-38','morbi','morbi',17,'Smith, Boehm and Monahan');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (172,'102-44','ut','sem',20,'Bartell, Crooks and Roob');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (173,'206-81','enim','accumsan',39,'Larson, Friesen and Schumm');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (174,'053-77','rhoncus','eu',67,'Halvorson-White');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (175,'766-76','quam','curae',24,'Hegmann-Vandervort');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (176,'491-66','sed','molestie',91,'Leuschke-Kuhic');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (177,'776-26','sapien','mi',88,'Considine, Bergnaum and Nicolas');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (178,'532-42','curae','nisl',83,'Dickinson, Berge and Rau');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (179,'976-39','suscipit','mauris',87,'Mills, Wehner and Marvin');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (180,'933-62','proin','aliquam',28,'Roberts-Rau');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (181,'029-51','leo','ultrices',29,'Marks LLC');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (182,'708-54','nec','amet',30,'Klein LLC');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (183,'890-38','fusce','justo',59,'Mann, Renner and O''Hara');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (184,'450-92','at','proin',09,'Ferry, Torphy and Kohler');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (185,'992-13','quis','ac',88,'Barrows, Parisian and Lemke');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (186,'356-44','convallis','pellentesque',00,'Gorczany Group');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (187,'415-11','nunc','curae',19,'Brakus LLC');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (188,'319-52','id','ipsum',66,'Rogahn, Senger and Bogan');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (189,'101-68','pede','sed',36,'Klein Inc');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (190,'826-82','pellentesque','condimentum',49,'Mohr-Lebsack');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (191,'859-71','diam','nisl',17,'Nolan-Schoen');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (192,'872-25','quisque','lectus',59,'Hills-Hettinger');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (193,'799-16','sociis','felis',53,'Kshlerin Group');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (194,'269-46','sapien','eros',60,'Prosacco Group');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (195,'657-63','quam','habitasse',44,'Rosenbaum LLC');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (196,'872-23','sapien','elit',35,'Purdy and Sons');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (197,'339-90','lectus','ac',17,'Kautzer-White');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (198,'469-77','augue','pulvinar',57,'Fadel, Schroeder and Gibson');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (199,'844-83','in','neque',81,'Hirthe and Sons');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (200,'685-33','elit','vivamus',66,'Reichert-Beer');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (201,'394-78','posuere','nisl',85,'Grimes-Hahn');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (202,'715-03','etiam','consequat',56,'Schmidt, Halvorson and Pouros');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (203,'092-95','aliquet','ipsum',57,'Baumbach and Sons');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (204,'871-21','a','phasellus',51,'Douglas and Sons');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (205,'835-82','pede','non',33,'Barrows-Boehm');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (206,'381-68','proin','curae',55,'Treutel-Kihn');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (207,'609-81','ac','vivamus',41,'Blanda Inc');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (208,'834-15','ullamcorper','sapien',43,'Hagenes Inc');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (209,'542-11','quam','lacus',94,'Robel-Gleichner');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (210,'759-26','curae','semper',35,'Connelly Group');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (211,'315-54','ante','erat',53,'Kunde, Bashirian and Dare');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (212,'295-78','platea','justo',37,'Schaden-Moore');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (213,'653-59','at','turpis',31,'Tillman Group');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (214,'788-11','sed','ac',02,'Marvin Group');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (215,'553-06','vitae','quam',99,'Runolfsdottir, Reynolds and Jakubowski');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (216,'893-43','penatibus','erat',70,'Farrell, Jast and Stracke');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (217,'273-01','risus','bibendum',72,'Hagenes-Stracke');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (218,'916-75','id','curabitur',85,'Prohaska and Sons');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (219,'163-03','diam','vel',27,'Luettgen Inc');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (220,'815-26','eu','erat',72,'Schamberger, Prosacco and Marks');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (221,'547-29','primis','morbi',03,'Predovic, Walsh and Berge');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (222,'872-01','sapien','vitae',65,'Marvin-Williamson');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (223,'735-56','ac','ac',22,'Stoltenberg, Hodkiewicz and Watsica');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (224,'652-99','ipsum','suscipit',43,'Howe, Bartell and Runte');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (225,'222-04','tempor','vestibulum',73,'Cruickshank-Stamm');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (226,'296-25','et','erat',96,'Rowe Inc');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (227,'152-69','morbi','convallis',80,'Sporer LLC');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (228,'887-65','pede','dapibus',68,'Durgan LLC');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (229,'588-90','tincidunt','donec',34,'Brown, Effertz and Blick');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (230,'862-15','volutpat','hac',06,'Hintz, Bins and Ratke');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (231,'775-91','ante','enim',18,'Gaylord, Baumbach and Kihn');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (232,'800-49','quis','ac',69,'Predovic Inc');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (233,'898-45','consectetuer','neque',43,'Oberbrunner and Sons');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (234,'275-69','eget','curabitur',50,'Abshire, Little and Considine');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (235,'746-06','varius','tincidunt',54,'Barton-Simonis');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (236,'203-22','lorem','aliquam',89,'Howe, Miller and Walter');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (237,'113-16','est','metus',56,'Sipes-Kunde');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (238,'000-70','quam','parturient',60,'Sanford-King');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (239,'138-22','nunc','vehicula',71,'Stehr-Wunsch');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (240,'204-69','proin','ante',79,'Gerlach and Sons');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (241,'701-70','tortor','vitae',42,'Ortiz-Grady');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (242,'475-02','pede','sapien',63,'Kozey, McGlynn and Pacocha');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (243,'399-81','donec','dolor',68,'Monahan, Terry and Konopelski');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (244,'777-10','mattis','morbi',37,'Champlin Group');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (245,'225-37','convallis','etiam',53,'Moen Group');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (246,'666-20','diam','tempus',96,'Breitenberg-Prohaska');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (247,'515-57','aliquet','at',27,'Hane-Emard');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (248,'647-72','id','penatibus',04,'Brown-Howell');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (249,'218-00','eros','nulla',43,'Streich-Wilkinson');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (250,'585-62','adipiscing','duis',48,'Baumbach, Paucek and Windler');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (251,'102-48','curabitur','penatibus',49,'Pagac-Feest');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (252,'348-63','eu','facilisi',63,'Gusikowski, Flatley and Hackett');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (253,'818-68','morbi','in',36,'Leffler Group');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (254,'127-72','justo','ligula',02,'Reilly-Nikolaus');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (255,'009-21','lectus','in',40,'Walker LLC');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (256,'554-24','turpis','massa',37,'Lang, West and Bednar');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (257,'806-31','vestibulum','massa',40,'Casper, Hoeger and Schiller');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (258,'064-17','odio','vel',70,'Thiel-Smith');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (259,'205-83','lectus','morbi',52,'Denesik and Sons');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (260,'301-65','blandit','ridiculus',85,'Haley-Cummings');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (261,'503-65','semper','in',34,'Schumm-Dietrich');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (262,'646-17','cubilia','quis',75,'Kulas, Barton and Dooley');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (263,'504-41','nec','duis',09,'Gislason, Hilpert and Raynor');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (264,'680-49','rutrum','cum',28,'Reilly, Berge and Goldner');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (265,'488-49','sapien','massa',73,'Smitham and Sons');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (266,'493-77','consequat','varius',88,'Graham, Fadel and Goyette');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (267,'504-76','leo','libero',97,'Jacobson LLC');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (268,'452-12','volutpat','magnis',36,'Homenick Group');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (269,'625-59','proin','aliquam',68,'Green and Sons');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (270,'504-69','et','integer',91,'Abshire-Renner');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (271,'642-13','dui','quam',45,'Nikolaus, Considine and Towne');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (272,'383-53','felis','eleifend',64,'Kautzer-Mraz');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (273,'146-82','proin','lorem',24,'Runolfsson-Senger');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (274,'941-48','at','mauris',62,'McCullough Inc');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (275,'402-64','morbi','turpis',27,'Christiansen, Hudson and Wiza');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (276,'174-27','diam','lacinia',49,'Blick-Hoeger');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (277,'455-34','odio','nec',52,'Ondricka, Dickinson and Hilpert');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (278,'922-82','interdum','eu',52,'Jacobson LLC');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (279,'732-54','eu','tortor',41,'Medhurst, Collier and Heidenreich');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (280,'623-62','lorem','eget',88,'Kuvalis, Strosin and Barrows');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (281,'153-95','dictumst','maecenas',02,'Kessler Inc');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (282,'399-21','lobortis','luctus',05,'Towne, Cummings and Wyman');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (283,'965-36','primis','eget',36,'Pouros, Blanda and Daugherty');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (284,'263-04','hac','sapien',11,'Metz, Bergstrom and Leannon');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (285,'634-03','donec','consequat',69,'Bayer-Beahan');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (286,'074-68','vitae','proin',72,'Upton-Pfannerstill');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (287,'493-92','viverra','vestibulum',18,'Hahn Group');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (288,'249-49','risus','vel',78,'Aufderhar and Sons');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (289,'672-56','suscipit','proin',37,'Swift Group');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (290,'782-61','semper','sapien',54,'McGlynn, Grady and Leffler');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (291,'323-38','amet','tempus',65,'Mertz-Shields');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (292,'657-97','maecenas','velit',70,'Waelchi and Sons');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (293,'640-79','turpis','lectus',73,'Nitzsche-Gaylord');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (294,'440-80','placerat','natoque',75,'Kautzer, Hermiston and Morar');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (295,'892-20','gravida','varius',39,'Abernathy-Abbott');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (296,'430-10','tincidunt','etiam',85,'Ryan Group');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (297,'931-02','neque','morbi',21,'Spencer-Watsica');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (298,'211-58','metus','ligula',99,'Hamill Inc');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (299,'090-32','eleifend','nulla',05,'Batz and Sons');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (300,'425-98','pulvinar','suspendisse',09,'Hodkiewicz Group');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (301,'220-38','nam','vestibulum',71,'Beahan and Sons');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (302,'159-86','cras','felis',60,'Casper-Purdy');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (303,'632-60','tincidunt','donec',00,'Heller, Beier and Medhurst');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (304,'667-11','vitae','erat',97,'Strosin LLC');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (305,'364-45','in','imperdiet',51,'Carter-Gottlieb');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (306,'206-76','nullam','semper',74,'Ward, Konopelski and Kunze');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (307,'649-95','duis','morbi',47,'Bernier Group');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (308,'283-88','magnis','ac',34,'Bailey Inc');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (309,'028-11','ultrices','rutrum',30,'Nader-Heaney');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (310,'329-42','donec','nibh',25,'Hermiston Group');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (311,'017-88','tincidunt','integer',63,'Hoppe-Shanahan');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (312,'109-19','ipsum','id',54,'Olson, Crona and Kozey');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (313,'721-79','duis','ac',31,'Schinner, Barrows and Hahn');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (314,'683-77','lobortis','praesent',73,'Price, Farrell and Rath');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (315,'677-21','vestibulum','quam',20,'Hartmann-Lindgren');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (316,'577-80','interdum','morbi',62,'Torp Group');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (317,'128-14','consequat','ullamcorper',10,'Blanda Inc');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (318,'083-04','blandit','sit',74,'Morar, Douglas and Frami');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (319,'196-74','in','in',33,'Olson-O''Kon');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (320,'664-15','maecenas','felis',14,'Baumbach Group');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (321,'341-70','pretium','at',96,'Morar and Sons');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (322,'335-92','est','erat',92,'Marks, Carter and Baumbach');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (323,'649-90','convallis','nulla',60,'Sawayn-Stokes');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (324,'077-46','consectetuer','vestibulum',35,'Upton-Corkery');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (325,'087-53','consequat','dolor',27,'Predovic, Satterfield and Orn');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (326,'073-23','elit','nulla',97,'Hammes, Walker and O''Conner');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (327,'483-23','maecenas','eget',18,'Johnson, Lesch and Bins');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (328,'736-26','orci','aliquet',07,'Herzog, Deckow and Mayer');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (329,'176-83','sit','curae',91,'Aufderhar, King and Herzog');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (330,'931-25','turpis','laoreet',24,'Schumm LLC');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (331,'644-44','eros','ut',23,'Lesch Inc');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (332,'607-92','ultrices','vestibulum',50,'Windler, Lehner and Waters');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (333,'597-50','in','nisl',55,'Goldner and Sons');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (334,'903-08','consequat','erat',16,'Purdy, Goodwin and VonRueden');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (335,'749-32','rutrum','augue',86,'Conroy Inc');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (336,'755-89','nunc','ut',24,'Emard Inc');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (337,'082-92','vestibulum','aliquet',96,'Pfannerstill Inc');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (338,'514-66','donec','nulla',38,'DuBuque, Monahan and Emmerich');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (339,'338-12','potenti','non',71,'Kulas-MacGyver');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (340,'082-43','gravida','porta',83,'O''Conner and Sons');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (341,'067-61','nulla','nascetur',30,'Stamm Inc');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (342,'093-18','nam','lorem',05,'Schinner and Sons');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (343,'810-14','aliquet','est',78,'Nitzsche, Von and Kessler');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (344,'843-33','massa','turpis',76,'Hand-Lind');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (345,'914-80','amet','non',14,'Mills, Labadie and Goyette');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (346,'608-89','vulputate','primis',28,'Johnston-Hayes');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (347,'906-61','ullamcorper','nisi',01,'Paucek and Sons');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (348,'714-45','montes','vulputate',85,'Ernser Group');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (349,'173-27','maecenas','habitasse',60,'Zboncak, Durgan and McGlynn');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (350,'431-59','ullamcorper','dapibus',78,'Hagenes, Wehner and Morissette');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (351,'704-30','leo','tortor',84,'Turner, Wisozk and Gerlach');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (352,'128-93','accumsan','lobortis',44,'Kunze and Sons');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (353,'390-50','eget','cursus',33,'Ratke Inc');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (354,'510-38','vestibulum','congue',55,'Durgan, Lueilwitz and Toy');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (355,'096-22','vitae','nulla',67,'Hansen, Stokes and Mann');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (356,'661-02','luctus','orci',48,'Luettgen-Blick');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (357,'720-68','posuere','accumsan',34,'Hansen-O''Hara');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (358,'134-33','dapibus','rutrum',44,'Cassin and Sons');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (359,'296-90','augue','nec',09,'Price Group');
INSERT INTO mytable(id,matricula,linea,modelo,capacidad,fabricante) VALUES (360,'906-51','suscipit','ultrices',45,'Grimes and Sons');
